version: '3.9'

services:
  redis_db1:
    image: redis:latest
    container_name: ${REDIS_HOST1}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - redis_data1:/data
    ports:
      - "${REDIS_PORT1}:${REDIS_DEFAULT_INTERNAL_PORT}"
    networks:
      - dws202-network

  redis_db2:
    image: redis:latest
    container_name: ${REDIS_HOST2}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - redis_data2:/data
    ports:
      - "${REDIS_PORT2}:${REDIS_DEFAULT_INTERNAL_PORT}"
    networks:
      - dws202-network

  script:
    build: .
    container_name: script
    env_file:
      - .env
    depends_on:
      - redis_db1
      - redis_db2
    networks:
      - dws202-network

networks:
  dws202-network:
    driver: bridge

volumes:
  redis_data1:
  redis_data2: